[project]
name = "blog"
version = "1.2"
description = "Blog du Yax"
readme = "README.md"
authors = [
    { name = "Yax" }
]
requires-python = ">=3.12.8"
dependencies = [
    "mistune>=3.0.2",
    "pygments>=2.18.0",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "black>=24.10.0",
]
